services:
  nextjs:
    container_name: nextjs_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    env_file:
      - .env
      - .env.local
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo:8.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  seeder:
    container_name: db_seeder
    build: .
    command: sh -c "sleep 5 && node scripts/seed.js"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/mydatabase?authSource=admin
    env_file:
      - .env
      - .env.local
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure:3
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
